import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import localfont from "next/font/local";
import path from "path";
import SideBar from "@/Components/SideBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
/* const Mona = localfont({
  src: [
    {
      path: "../../public/Mona Sarif/Mona-San",
      weight: "200",
    },
    {
      path: "../../public/Mona Sarif/",
      weight: "300",
    },
    {
      path: "../../public/Mona Sarif/Mona-Sans-Black.woff",
      weight: "400",
    },
    {
      path: "../../public/Mona Sarif/Mona-Sans-Black.woff",
      weight: "500",
    },
  ],
  variable: "--font-mona", // Custom property for the font
}); */
const Mona = localfont({
  src: [
    { path: "../../public/Mona Sarif/Mona-Sans.woff", weight: "200" },
    {
      path: "../../public/Mona Sarif/Mona-Sans-Medium.woff",
      weight: "400",
    },
    { path: "../../public/Mona Sarif/Mona-Sans-Regular.woff", weight: "300" },
    { path: "../../public/Mona Sarif/Mona-Sans-Bold.woff", weight: "600" },
    { path: "../../public/Mona Sarif/Mona-Sans-SemiBold.woff", weight: "500" },
  ],
  variable: "--font-mona",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Mona.variable}>
        <div>
          <div className="hidden lg:block bg-black fixed h-full xl:w-[15%] w-full lg:w-1/5">
          <SideBar />
          </div>
          <div className="xl:ml-[15%] lg:ml-[20%] pb-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
